apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: single-

resources:
  - ../../bases/deployment/
  - ./ingress.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nextjs-website
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: single-nextjs-website
        template:
          metadata:
            labels:
              app: single-nextjs-website
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: nextjs-website-service
      spec:
        selector:
          app: single-nextjs-website
      